package com.quant.platform.ai.core.client.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;

/**
 * 东财 F10 利润表（{@code RPT_F10_FINANCE_GINCOME}）单行，字段与接口 {@code data} 一致。
 * <p>
 * 金额类字段单位与报表币种一致（一般为元）；同比字段后缀 {@code _YOY} 为同比增长率（%）。
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record EastmoneyF10GIncomeRowDTO(
        /** 带市场后缀证券代码 */
        @JsonProperty("SECUCODE") String secucode,
        /** 证券 6 位代码 */
        @JsonProperty("SECURITY_CODE") String securityCode,
        /** 证券简称 */
        @JsonProperty("SECURITY_NAME_ABBR") String securityNameAbbr,
        /** 机构编码 */
        @JsonProperty("ORG_CODE") String orgCode,
        /** 机构类型，如「通用」 */
        @JsonProperty("ORG_TYPE") String orgType,
        /** 报告期（接口原样） */
        @JsonProperty("REPORT_DATE") String reportDate,
        /** 报告类型，如「一季报」「年报」 */
        @JsonProperty("REPORT_TYPE") String reportType,
        /** 报告期展示名 */
        @JsonProperty("REPORT_DATE_NAME") String reportDateName,
        @JsonProperty("SECURITY_TYPE_CODE") String securityTypeCode,
        /** 公告日期 */
        @JsonProperty("NOTICE_DATE") String noticeDate,
        /** 数据更新日期 */
        @JsonProperty("UPDATE_DATE") String updateDate,
        /** 币种，如 CNY */
        @JsonProperty("CURRENCY") String currency,
        /** 营业总收入 */
        @JsonProperty("TOTAL_OPERATE_INCOME") BigDecimal totalOperateIncome,
        @JsonProperty("TOTAL_OPERATE_INCOME_YOY") BigDecimal totalOperateIncomeYoy,
        /** 营业收入 */
        @JsonProperty("OPERATE_INCOME") BigDecimal operateIncome,
        @JsonProperty("OPERATE_INCOME_YOY") BigDecimal operateIncomeYoy,
        /** 利息收入 */
        @JsonProperty("INTEREST_INCOME") BigDecimal interestIncome,
        @JsonProperty("INTEREST_INCOME_YOY") BigDecimal interestIncomeYoy,
        /** 已赚保费 */
        @JsonProperty("EARNED_PREMIUM") BigDecimal earnedPremium,
        @JsonProperty("EARNED_PREMIUM_YOY") BigDecimal earnedPremiumYoy,
        /** 手续费及佣金收入 */
        @JsonProperty("FEE_COMMISSION_INCOME") BigDecimal feeCommissionIncome,
        @JsonProperty("FEE_COMMISSION_INCOME_YOY") BigDecimal feeCommissionIncomeYoy,
        /** 其他业务收入 */
        @JsonProperty("OTHER_BUSINESS_INCOME") BigDecimal otherBusinessIncome,
        @JsonProperty("OTHER_BUSINESS_INCOME_YOY") BigDecimal otherBusinessIncomeYoy,
        @JsonProperty("TOI_OTHER") BigDecimal toiOther,
        @JsonProperty("TOI_OTHER_YOY") BigDecimal toiOtherYoy,
        /** 营业总成本 */
        @JsonProperty("TOTAL_OPERATE_COST") BigDecimal totalOperateCost,
        @JsonProperty("TOTAL_OPERATE_COST_YOY") BigDecimal totalOperateCostYoy,
        /** 营业成本 */
        @JsonProperty("OPERATE_COST") BigDecimal operateCost,
        @JsonProperty("OPERATE_COST_YOY") BigDecimal operateCostYoy,
        /** 利息支出 */
        @JsonProperty("INTEREST_EXPENSE") BigDecimal interestExpense,
        @JsonProperty("INTEREST_EXPENSE_YOY") BigDecimal interestExpenseYoy,
        /** 手续费及佣金支出 */
        @JsonProperty("FEE_COMMISSION_EXPENSE") BigDecimal feeCommissionExpense,
        @JsonProperty("FEE_COMMISSION_EXPENSE_YOY") BigDecimal feeCommissionExpenseYoy,
        /** 研发费用 */
        @JsonProperty("RESEARCH_EXPENSE") BigDecimal researchExpense,
        @JsonProperty("RESEARCH_EXPENSE_YOY") BigDecimal researchExpenseYoy,
        @JsonProperty("SURRENDER_VALUE") BigDecimal surrenderValue,
        @JsonProperty("SURRENDER_VALUE_YOY") BigDecimal surrenderValueYoy,
        @JsonProperty("NET_COMPENSATE_EXPENSE") BigDecimal netCompensateExpense,
        @JsonProperty("NET_COMPENSATE_EXPENSE_YOY") BigDecimal netCompensateExpenseYoy,
        @JsonProperty("NET_CONTRACT_RESERVE") BigDecimal netContractReserve,
        @JsonProperty("NET_CONTRACT_RESERVE_YOY") BigDecimal netContractReserveYoy,
        @JsonProperty("POLICY_BONUS_EXPENSE") BigDecimal policyBonusExpense,
        @JsonProperty("POLICY_BONUS_EXPENSE_YOY") BigDecimal policyBonusExpenseYoy,
        @JsonProperty("REINSURE_EXPENSE") BigDecimal reinsureExpense,
        @JsonProperty("REINSURE_EXPENSE_YOY") BigDecimal reinsureExpenseYoy,
        @JsonProperty("OTHER_BUSINESS_COST") BigDecimal otherBusinessCost,
        @JsonProperty("OTHER_BUSINESS_COST_YOY") BigDecimal otherBusinessCostYoy,
        /** 税金及附加 */
        @JsonProperty("OPERATE_TAX_ADD") BigDecimal operateTaxAdd,
        @JsonProperty("OPERATE_TAX_ADD_YOY") BigDecimal operateTaxAddYoy,
        /** 销售费用 */
        @JsonProperty("SALE_EXPENSE") BigDecimal saleExpense,
        @JsonProperty("SALE_EXPENSE_YOY") BigDecimal saleExpenseYoy,
        /** 管理费用 */
        @JsonProperty("MANAGE_EXPENSE") BigDecimal manageExpense,
        @JsonProperty("MANAGE_EXPENSE_YOY") BigDecimal manageExpenseYoy,
        @JsonProperty("ME_RESEARCH_EXPENSE") BigDecimal meResearchExpense,
        @JsonProperty("ME_RESEARCH_EXPENSE_YOY") BigDecimal meResearchExpenseYoy,
        /** 财务费用 */
        @JsonProperty("FINANCE_EXPENSE") BigDecimal financeExpense,
        @JsonProperty("FINANCE_EXPENSE_YOY") BigDecimal financeExpenseYoy,
        /** 其中：利息费用 */
        @JsonProperty("FE_INTEREST_EXPENSE") BigDecimal feInterestExpense,
        @JsonProperty("FE_INTEREST_EXPENSE_YOY") BigDecimal feInterestExpenseYoy,
        /** 其中：利息收入 */
        @JsonProperty("FE_INTEREST_INCOME") BigDecimal feInterestIncome,
        @JsonProperty("FE_INTEREST_INCOME_YOY") BigDecimal feInterestIncomeYoy,
        /** 资产减值损失（旧口径，历史报表可能仍有值） */
        @JsonProperty("ASSET_IMPAIRMENT_LOSS") BigDecimal assetImpairmentLoss,
        /** 资产减值损失（旧口径），同比（%） */
        @JsonProperty("ASSET_IMPAIRMENT_LOSS_YOY") BigDecimal assetImpairmentLossYoy,
        /** 信用减值损失（旧口径，历史报表可能仍有值） */
        @JsonProperty("CREDIT_IMPAIRMENT_LOSS") BigDecimal creditImpairmentLoss,
        /** 信用减值损失（旧口径），同比（%） */
        @JsonProperty("CREDIT_IMPAIRMENT_LOSS_YOY") BigDecimal creditImpairmentLossYoy,
        @JsonProperty("TOC_OTHER") BigDecimal tocOther,
        @JsonProperty("TOC_OTHER_YOY") BigDecimal tocOtherYoy,
        /** 公允价值变动收益 */
        @JsonProperty("FAIRVALUE_CHANGE_INCOME") BigDecimal fairvalueChangeIncome,
        @JsonProperty("FAIRVALUE_CHANGE_INCOME_YOY") BigDecimal fairvalueChangeIncomeYoy,
        /** 投资收益 */
        @JsonProperty("INVEST_INCOME") BigDecimal investIncome,
        @JsonProperty("INVEST_INCOME_YOY") BigDecimal investIncomeYoy,
        /** 对联营企业和合营企业的投资收益 */
        @JsonProperty("INVEST_JOINT_INCOME") BigDecimal investJointIncome,
        @JsonProperty("INVEST_JOINT_INCOME_YOY") BigDecimal investJointIncomeYoy,
        @JsonProperty("NET_EXPOSURE_INCOME") BigDecimal netExposureIncome,
        @JsonProperty("NET_EXPOSURE_INCOME_YOY") BigDecimal netExposureIncomeYoy,
        /** 汇兑收益 */
        @JsonProperty("EXCHANGE_INCOME") BigDecimal exchangeIncome,
        @JsonProperty("EXCHANGE_INCOME_YOY") BigDecimal exchangeIncomeYoy,
        /** 资产处置收益 */
        @JsonProperty("ASSET_DISPOSAL_INCOME") BigDecimal assetDisposalIncome,
        @JsonProperty("ASSET_DISPOSAL_INCOME_YOY") BigDecimal assetDisposalIncomeYoy,
        /** 资产减值损失（新） */
        @JsonProperty("ASSET_IMPAIRMENT_INCOME") BigDecimal assetImpairmentIncome,
        /** 资产减值损失（新），同比（%） */
        @JsonProperty("ASSET_IMPAIRMENT_INCOME_YOY") BigDecimal assetImpairmentIncomeYoy,
        /** 信用减值损失（新） */
        @JsonProperty("CREDIT_IMPAIRMENT_INCOME") BigDecimal creditImpairmentIncome,
        /** 信用减值损失（新），同比（%） */
        @JsonProperty("CREDIT_IMPAIRMENT_INCOME_YOY") BigDecimal creditImpairmentIncomeYoy,
        /** 其他收益 */
        @JsonProperty("OTHER_INCOME") BigDecimal otherIncome,
        @JsonProperty("OTHER_INCOME_YOY") BigDecimal otherIncomeYoy,
        @JsonProperty("OPERATE_PROFIT_OTHER") BigDecimal operateProfitOther,
        @JsonProperty("OPERATE_PROFIT_OTHER_YOY") BigDecimal operateProfitOtherYoy,
        @JsonProperty("OPERATE_PROFIT_BALANCE") BigDecimal operateProfitBalance,
        @JsonProperty("OPERATE_PROFIT_BALANCE_YOY") BigDecimal operateProfitBalanceYoy,
        /** 营业利润 */
        @JsonProperty("OPERATE_PROFIT") BigDecimal operateProfit,
        @JsonProperty("OPERATE_PROFIT_YOY") BigDecimal operateProfitYoy,
        /** 营业外收入 */
        @JsonProperty("NONBUSINESS_INCOME") BigDecimal nonbusinessIncome,
        @JsonProperty("NONBUSINESS_INCOME_YOY") BigDecimal nonbusinessIncomeYoy,
        @JsonProperty("NONCURRENT_DISPOSAL_INCOME") BigDecimal noncurrentDisposalIncome,
        @JsonProperty("NONCURRENT_DISPOSAL_INCOME_YOY") BigDecimal noncurrentDisposalIncomeYoy,
        /** 营业外支出 */
        @JsonProperty("NONBUSINESS_EXPENSE") BigDecimal nonbusinessExpense,
        @JsonProperty("NONBUSINESS_EXPENSE_YOY") BigDecimal nonbusinessExpenseYoy,
        @JsonProperty("NONCURRENT_DISPOSAL_LOSS") BigDecimal noncurrentDisposalLoss,
        @JsonProperty("NONCURRENT_DISPOSAL_LOSS_YOY") BigDecimal noncurrentDisposalLossYoy,
        @JsonProperty("EFFECT_TP_OTHER") BigDecimal effectTpOther,
        @JsonProperty("EFFECT_TP_OTHER_YOY") BigDecimal effectTpOtherYoy,
        @JsonProperty("TOTAL_PROFIT_BALANCE") BigDecimal totalProfitBalance,
        @JsonProperty("TOTAL_PROFIT_BALANCE_YOY") BigDecimal totalProfitBalanceYoy,
        /** 利润总额 */
        @JsonProperty("TOTAL_PROFIT") BigDecimal totalProfit,
        @JsonProperty("TOTAL_PROFIT_YOY") BigDecimal totalProfitYoy,
        /** 所得税费用 */
        @JsonProperty("INCOME_TAX") BigDecimal incomeTax,
        @JsonProperty("INCOME_TAX_YOY") BigDecimal incomeTaxYoy,
        @JsonProperty("EFFECT_NETPROFIT_OTHER") BigDecimal effectNetprofitOther,
        @JsonProperty("EFFECT_NETPROFIT_OTHER_YOY") BigDecimal effectNetprofitOtherYoy,
        @JsonProperty("EFFECT_NETPROFIT_BALANCE") BigDecimal effectNetprofitBalance,
        @JsonProperty("EFFECT_NETPROFIT_BALANCE_YOY") BigDecimal effectNetprofitBalanceYoy,
        @JsonProperty("UNCONFIRM_INVEST_LOSS") BigDecimal unconfirmInvestLoss,
        @JsonProperty("UNCONFIRM_INVEST_LOSS_YOY") BigDecimal unconfirmInvestLossYoy,
        /** 净利润 */
        @JsonProperty("NETPROFIT") BigDecimal netprofit,
        @JsonProperty("NETPROFIT_YOY") BigDecimal netprofitYoy,
        @JsonProperty("PRECOMBINE_PROFIT") BigDecimal precombineProfit,
        @JsonProperty("PRECOMBINE_PROFIT_YOY") BigDecimal precombineProfitYoy,
        /** 持续经营净利润 */
        @JsonProperty("CONTINUED_NETPROFIT") BigDecimal continuedNetprofit,
        @JsonProperty("CONTINUED_NETPROFIT_YOY") BigDecimal continuedNetprofitYoy,
        @JsonProperty("DISCONTINUED_NETPROFIT") BigDecimal discontinuedNetprofit,
        @JsonProperty("DISCONTINUED_NETPROFIT_YOY") BigDecimal discontinuedNetprofitYoy,
        /** 归属于母公司股东的净利润 */
        @JsonProperty("PARENT_NETPROFIT") BigDecimal parentNetprofit,
        @JsonProperty("PARENT_NETPROFIT_YOY") BigDecimal parentNetprofitYoy,
        /** 少数股东损益 */
        @JsonProperty("MINORITY_INTEREST") BigDecimal minorityInterest,
        @JsonProperty("MINORITY_INTEREST_YOY") BigDecimal minorityInterestYoy,
        /** 扣非后归属母公司净利润 */
        @JsonProperty("DEDUCT_PARENT_NETPROFIT") BigDecimal deductParentNetprofit,
        @JsonProperty("DEDUCT_PARENT_NETPROFIT_YOY") BigDecimal deductParentNetprofitYoy,
        @JsonProperty("NETPROFIT_OTHER") BigDecimal netprofitOther,
        @JsonProperty("NETPROFIT_OTHER_YOY") BigDecimal netprofitOtherYoy,
        @JsonProperty("NETPROFIT_BALANCE") BigDecimal netprofitBalance,
        @JsonProperty("NETPROFIT_BALANCE_YOY") BigDecimal netprofitBalanceYoy,
        /** 基本每股收益（元） */
        @JsonProperty("BASIC_EPS") BigDecimal basicEps,
        @JsonProperty("BASIC_EPS_YOY") BigDecimal basicEpsYoy,
        /** 稀释每股收益（元） */
        @JsonProperty("DILUTED_EPS") BigDecimal dilutedEps,
        @JsonProperty("DILUTED_EPS_YOY") BigDecimal dilutedEpsYoy,
        /** 其他综合收益 */
        @JsonProperty("OTHER_COMPRE_INCOME") BigDecimal otherCompreIncome,
        @JsonProperty("OTHER_COMPRE_INCOME_YOY") BigDecimal otherCompreIncomeYoy,
        @JsonProperty("PARENT_OCI") BigDecimal parentOci,
        @JsonProperty("PARENT_OCI_YOY") BigDecimal parentOciYoy,
        @JsonProperty("MINORITY_OCI") BigDecimal minorityOci,
        @JsonProperty("MINORITY_OCI_YOY") BigDecimal minorityOciYoy,
        @JsonProperty("PARENT_OCI_OTHER") BigDecimal parentOciOther,
        @JsonProperty("PARENT_OCI_OTHER_YOY") BigDecimal parentOciOtherYoy,
        @JsonProperty("PARENT_OCI_BALANCE") BigDecimal parentOciBalance,
        @JsonProperty("PARENT_OCI_BALANCE_YOY") BigDecimal parentOciBalanceYoy,
        @JsonProperty("UNABLE_OCI") BigDecimal unableOci,
        @JsonProperty("UNABLE_OCI_YOY") BigDecimal unableOciYoy,
        @JsonProperty("CREDITRISK_FAIRVALUE_CHANGE") BigDecimal creditriskFairvalueChange,
        @JsonProperty("CREDITRISK_FAIRVALUE_CHANGE_YOY") BigDecimal creditriskFairvalueChangeYoy,
        @JsonProperty("OTHERRIGHT_FAIRVALUE_CHANGE") BigDecimal otherrightFairvalueChange,
        @JsonProperty("OTHERRIGHT_FAIRVALUE_CHANGE_YOY") BigDecimal otherrightFairvalueChangeYoy,
        @JsonProperty("SETUP_PROFIT_CHANGE") BigDecimal setupProfitChange,
        @JsonProperty("SETUP_PROFIT_CHANGE_YOY") BigDecimal setupProfitChangeYoy,
        @JsonProperty("RIGHTLAW_UNABLE_OCI") BigDecimal rightlawUnableOci,
        @JsonProperty("RIGHTLAW_UNABLE_OCI_YOY") BigDecimal rightlawUnableOciYoy,
        @JsonProperty("UNABLE_OCI_OTHER") BigDecimal unableOciOther,
        @JsonProperty("UNABLE_OCI_OTHER_YOY") BigDecimal unableOciOtherYoy,
        @JsonProperty("UNABLE_OCI_BALANCE") BigDecimal unableOciBalance,
        @JsonProperty("UNABLE_OCI_BALANCE_YOY") BigDecimal unableOciBalanceYoy,
        @JsonProperty("ABLE_OCI") BigDecimal ableOci,
        @JsonProperty("ABLE_OCI_YOY") BigDecimal ableOciYoy,
        @JsonProperty("RIGHTLAW_ABLE_OCI") BigDecimal rightlawAbleOci,
        @JsonProperty("RIGHTLAW_ABLE_OCI_YOY") BigDecimal rightlawAbleOciYoy,
        @JsonProperty("AFA_FAIRVALUE_CHANGE") BigDecimal afaFairvalueChange,
        @JsonProperty("AFA_FAIRVALUE_CHANGE_YOY") BigDecimal afaFairvalueChangeYoy,
        @JsonProperty("HMI_AFA") BigDecimal hmiAfa,
        @JsonProperty("HMI_AFA_YOY") BigDecimal hmiAfaYoy,
        @JsonProperty("CASHFLOW_HEDGE_VALID") BigDecimal cashflowHedgeValid,
        @JsonProperty("CASHFLOW_HEDGE_VALID_YOY") BigDecimal cashflowHedgeValidYoy,
        @JsonProperty("CREDITOR_FAIRVALUE_CHANGE") BigDecimal creditorFairvalueChange,
        @JsonProperty("CREDITOR_FAIRVALUE_CHANGE_YOY") BigDecimal creditorFairvalueChangeYoy,
        @JsonProperty("CREDITOR_IMPAIRMENT_RESERVE") BigDecimal creditorImpairmentReserve,
        @JsonProperty("CREDITOR_IMPAIRMENT_RESERVE_YOY") BigDecimal creditorImpairmentReserveYoy,
        @JsonProperty("FINANCE_OCI_AMT") BigDecimal financeOciAmt,
        @JsonProperty("FINANCE_OCI_AMT_YOY") BigDecimal financeOciAmtYoy,
        /** 外币报表折算差额 */
        @JsonProperty("CONVERT_DIFF") BigDecimal convertDiff,
        @JsonProperty("CONVERT_DIFF_YOY") BigDecimal convertDiffYoy,
        @JsonProperty("ABLE_OCI_OTHER") BigDecimal ableOciOther,
        @JsonProperty("ABLE_OCI_OTHER_YOY") BigDecimal ableOciOtherYoy,
        @JsonProperty("ABLE_OCI_BALANCE") BigDecimal ableOciBalance,
        @JsonProperty("ABLE_OCI_BALANCE_YOY") BigDecimal ableOciBalanceYoy,
        @JsonProperty("OCI_OTHER") BigDecimal ociOther,
        @JsonProperty("OCI_OTHER_YOY") BigDecimal ociOtherYoy,
        @JsonProperty("OCI_BALANCE") BigDecimal ociBalance,
        @JsonProperty("OCI_BALANCE_YOY") BigDecimal ociBalanceYoy,
        /** 综合收益总额 */
        @JsonProperty("TOTAL_COMPRE_INCOME") BigDecimal totalCompreIncome,
        @JsonProperty("TOTAL_COMPRE_INCOME_YOY") BigDecimal totalCompreIncomeYoy,
        @JsonProperty("PARENT_TCI") BigDecimal parentTci,
        @JsonProperty("PARENT_TCI_YOY") BigDecimal parentTciYoy,
        @JsonProperty("MINORITY_TCI") BigDecimal minorityTci,
        @JsonProperty("MINORITY_TCI_YOY") BigDecimal minorityTciYoy,
        @JsonProperty("PRECOMBINE_TCI") BigDecimal precombineTci,
        @JsonProperty("PRECOMBINE_TCI_YOY") BigDecimal precombineTciYoy,
        @JsonProperty("EFFECT_TCI_BALANCE") BigDecimal effectTciBalance,
        @JsonProperty("EFFECT_TCI_BALANCE_YOY") BigDecimal effectTciBalanceYoy,
        @JsonProperty("TCI_OTHER") BigDecimal tciOther,
        @JsonProperty("TCI_OTHER_YOY") BigDecimal tciOtherYoy,
        @JsonProperty("TCI_BALANCE") BigDecimal tciBalance,
        @JsonProperty("TCI_BALANCE_YOY") BigDecimal tciBalanceYoy,
        @JsonProperty("ACF_END_INCOME") BigDecimal acfEndIncome,
        @JsonProperty("ACF_END_INCOME_YOY") BigDecimal acfEndIncomeYoy,
        /** 审计意见类型 */
        @JsonProperty("OPINION_TYPE") String opinionType) {
}
