package com.quant.platform.ai.core.client.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;

/**
 * 东财 F10 现金流量表（{@code RPT_F10_FINANCE_GCASHFLOW}）单行，字段与接口 {@code data} 一致。
 * <p>
 * 金额类字段单位与报表币种一致（一般为元）；字段后缀 {@code _YOY} 为同比增长率（%）。
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record EastmoneyF10GCashflowRowDTO(
        /** 带市场后缀证券代码 */
        @JsonProperty("SECUCODE") String secucode,
        /** 证券 6 位代码 */
        @JsonProperty("SECURITY_CODE") String securityCode,
        /** 证券简称 */
        @JsonProperty("SECURITY_NAME_ABBR") String securityNameAbbr,
        /** 机构编码 */
        @JsonProperty("ORG_CODE") String orgCode,
        /** 机构类型，如「通用」 */
        @JsonProperty("ORG_TYPE") String orgType,
        /** 报告期（接口原样） */
        @JsonProperty("REPORT_DATE") String reportDate,
        /** 报告类型，如「一季报」 */
        @JsonProperty("REPORT_TYPE") String reportType,
        /** 报告期展示名 */
        @JsonProperty("REPORT_DATE_NAME") String reportDateName,
        /** 证券类型编码 */
        @JsonProperty("SECURITY_TYPE_CODE") String securityTypeCode,
        /** 公告日期 */
        @JsonProperty("NOTICE_DATE") String noticeDate,
        /** 数据更新日期 */
        @JsonProperty("UPDATE_DATE") String updateDate,
        /** 币种，如 CNY */
        @JsonProperty("CURRENCY") String currency,
        /** 销售商品、提供劳务收到的现金 */
        @JsonProperty("SALES_SERVICES") BigDecimal salesServices,
        /** 客户存款和同业存放款项净增加额 */
        @JsonProperty("DEPOSIT_INTERBANK_ADD") BigDecimal depositInterbankAdd,
        /** 向中央银行借款净增加额 */
        @JsonProperty("LOAN_PBC_ADD") BigDecimal loanPbcAdd,
        /** 向其他金融机构拆入资金净增加额 */
        @JsonProperty("OFI_BF_ADD") BigDecimal ofiBfAdd,
        /** 收到原保险合同保费取得的现金 */
        @JsonProperty("RECEIVE_ORIGIC_PREMIUM") BigDecimal receiveOrigicPremium,
        /** 收到再保险业务现金净额 */
        @JsonProperty("RECEIVE_REINSURE_NET") BigDecimal receiveReinsureNet,
        /** 保户储金及投资款净增加额 */
        @JsonProperty("INSURED_INVEST_ADD") BigDecimal insuredInvestAdd,
        /** 处置交易性金融资产净增加额 */
        @JsonProperty("DISPOSAL_TFA_ADD") BigDecimal disposalTfaAdd,
        /** 收取利息、手续费及佣金的现金 */
        @JsonProperty("RECEIVE_INTEREST_COMMISSION") BigDecimal receiveInterestCommission,
        /** 拆入资金净增加额 */
        @JsonProperty("BORROW_FUND_ADD") BigDecimal borrowFundAdd,
        /** 发放贷款及垫款净减少额 */
        @JsonProperty("LOAN_ADVANCE_REDUCE") BigDecimal loanAdvanceReduce,
        /** 回购业务资金净增加额 */
        @JsonProperty("REPO_BUSINESS_ADD") BigDecimal repoBusinessAdd,
        /** 收到的税费返还 */
        @JsonProperty("RECEIVE_TAX_REFUND") BigDecimal receiveTaxRefund,
        /** 收到其他与经营活动有关的现金 */
        @JsonProperty("RECEIVE_OTHER_OPERATE") BigDecimal receiveOtherOperate,
        /** 经营活动现金流入其他项目 */
        @JsonProperty("OPERATE_INFLOW_OTHER") BigDecimal operateInflowOther,
        /** 经营活动现金流入平衡项目 */
        @JsonProperty("OPERATE_INFLOW_BALANCE") BigDecimal operateInflowBalance,
        /** 经营活动现金流入小计 */
        @JsonProperty("TOTAL_OPERATE_INFLOW") BigDecimal totalOperateInflow,
        /** 购买商品、接受劳务支付的现金 */
        @JsonProperty("BUY_SERVICES") BigDecimal buyServices,
        /** 客户贷款及垫款净增加额 */
        @JsonProperty("LOAN_ADVANCE_ADD") BigDecimal loanAdvanceAdd,
        /** 存放中央银行和同业款项净增加额 */
        @JsonProperty("PBC_INTERBANK_ADD") BigDecimal pbcInterbankAdd,
        /** 支付原保险合同赔付款项的现金 */
        @JsonProperty("PAY_ORIGIC_COMPENSATE") BigDecimal payOrigicCompensate,
        /** 支付利息、手续费及佣金的现金 */
        @JsonProperty("PAY_INTEREST_COMMISSION") BigDecimal payInterestCommission,
        /** 支付保单红利的现金 */
        @JsonProperty("PAY_POLICY_BONUS") BigDecimal payPolicyBonus,
        /** 支付给职工以及为职工支付的现金 */
        @JsonProperty("PAY_STAFF_CASH") BigDecimal payStaffCash,
        /** 支付的各项税费 */
        @JsonProperty("PAY_ALL_TAX") BigDecimal payAllTax,
        /** 支付其他与经营活动有关的现金 */
        @JsonProperty("PAY_OTHER_OPERATE") BigDecimal payOtherOperate,
        /** 经营活动现金流出其他项目 */
        @JsonProperty("OPERATE_OUTFLOW_OTHER") BigDecimal operateOutflowOther,
        /** 经营活动现金流出平衡项目 */
        @JsonProperty("OPERATE_OUTFLOW_BALANCE") BigDecimal operateOutflowBalance,
        /** 经营活动现金流出小计 */
        @JsonProperty("TOTAL_OPERATE_OUTFLOW") BigDecimal totalOperateOutflow,
        /** 经营活动产生的现金流量净额其他项目 */
        @JsonProperty("OPERATE_NETCASH_OTHER") BigDecimal operateNetcashOther,
        /** 经营活动产生的现金流量净额平衡项目 */
        @JsonProperty("OPERATE_NETCASH_BALANCE") BigDecimal operateNetcashBalance,
        /** 经营活动产生的现金流量净额 */
        @JsonProperty("NETCASH_OPERATE") BigDecimal netcashOperate,
        /** 收回投资收到的现金 */
        @JsonProperty("WITHDRAW_INVEST") BigDecimal withdrawInvest,
        /** 取得投资收益收到的现金 */
        @JsonProperty("RECEIVE_INVEST_INCOME") BigDecimal receiveInvestIncome,
        /** 处置固定资产、无形资产和其他长期资产收回的现金净额 */
        @JsonProperty("DISPOSAL_LONG_ASSET") BigDecimal disposalLongAsset,
        /** 处置子公司及其他营业单位收到的现金净额 */
        @JsonProperty("DISPOSAL_SUBSIDIARY_OTHER") BigDecimal disposalSubsidiaryOther,
        /** 减少质押和定期存款所收到的现金 */
        @JsonProperty("REDUCE_PLEDGE_TIMEDEPOSITS") BigDecimal reducePledgeTimedeposits,
        /** 收到其他与投资活动有关的现金 */
        @JsonProperty("RECEIVE_OTHER_INVEST") BigDecimal receiveOtherInvest,
        /** 投资活动现金流入其他项目 */
        @JsonProperty("INVEST_INFLOW_OTHER") BigDecimal investInflowOther,
        /** 投资活动现金流入平衡项目 */
        @JsonProperty("INVEST_INFLOW_BALANCE") BigDecimal investInflowBalance,
        /** 投资活动现金流入小计 */
        @JsonProperty("TOTAL_INVEST_INFLOW") BigDecimal totalInvestInflow,
        /** 购建固定资产、无形资产和其他长期资产支付的现金 */
        @JsonProperty("CONSTRUCT_LONG_ASSET") BigDecimal constructLongAsset,
        /** 投资支付的现金 */
        @JsonProperty("INVEST_PAY_CASH") BigDecimal investPayCash,
        /** 质押贷款净增加额 */
        @JsonProperty("PLEDGE_LOAN_ADD") BigDecimal pledgeLoanAdd,
        /** 取得子公司及其他营业单位支付的现金净额 */
        @JsonProperty("OBTAIN_SUBSIDIARY_OTHER") BigDecimal obtainSubsidiaryOther,
        /** 增加质押和定期存款所支付的现金 */
        @JsonProperty("ADD_PLEDGE_TIMEDEPOSITS") BigDecimal addPledgeTimedeposits,
        /** 支付其他与投资活动有关的现金 */
        @JsonProperty("PAY_OTHER_INVEST") BigDecimal payOtherInvest,
        /** 投资活动现金流出其他项目 */
        @JsonProperty("INVEST_OUTFLOW_OTHER") BigDecimal investOutflowOther,
        /** 投资活动现金流出平衡项目 */
        @JsonProperty("INVEST_OUTFLOW_BALANCE") BigDecimal investOutflowBalance,
        /** 投资活动现金流出小计 */
        @JsonProperty("TOTAL_INVEST_OUTFLOW") BigDecimal totalInvestOutflow,
        /** 投资活动产生的现金流量净额其他项目 */
        @JsonProperty("INVEST_NETCASH_OTHER") BigDecimal investNetcashOther,
        /** 投资活动产生的现金流量净额平衡项目 */
        @JsonProperty("INVEST_NETCASH_BALANCE") BigDecimal investNetcashBalance,
        /** 投资活动产生的现金流量净额 */
        @JsonProperty("NETCASH_INVEST") BigDecimal netcashInvest,
        /** 吸收投资收到的现金 */
        @JsonProperty("ACCEPT_INVEST_CASH") BigDecimal acceptInvestCash,
        /** 其中：子公司吸收少数股东投资收到的现金 */
        @JsonProperty("SUBSIDIARY_ACCEPT_INVEST") BigDecimal subsidiaryAcceptInvest,
        /** 取得借款收到的现金 */
        @JsonProperty("RECEIVE_LOAN_CASH") BigDecimal receiveLoanCash,
        /** 发行债券收到的现金 */
        @JsonProperty("ISSUE_BOND") BigDecimal issueBond,
        /** 收到其他与筹资活动有关的现金 */
        @JsonProperty("RECEIVE_OTHER_FINANCE") BigDecimal receiveOtherFinance,
        /** 筹资活动现金流入其他项目 */
        @JsonProperty("FINANCE_INFLOW_OTHER") BigDecimal financeInflowOther,
        /** 筹资活动现金流入平衡项目 */
        @JsonProperty("FINANCE_INFLOW_BALANCE") BigDecimal financeInflowBalance,
        /** 筹资活动现金流入小计 */
        @JsonProperty("TOTAL_FINANCE_INFLOW") BigDecimal totalFinanceInflow,
        /** 偿还债务支付的现金 */
        @JsonProperty("PAY_DEBT_CASH") BigDecimal payDebtCash,
        /** 分配股利、利润或偿付利息支付的现金 */
        @JsonProperty("ASSIGN_DIVIDEND_PORFIT") BigDecimal assignDividendPorfit,
        /** 其中：子公司支付给少数股东的股利、利润 */
        @JsonProperty("SUBSIDIARY_PAY_DIVIDEND") BigDecimal subsidiaryPayDividend,
        /** 购买子公司少数股权支付的现金 */
        @JsonProperty("BUY_SUBSIDIARY_EQUITY") BigDecimal buySubsidiaryEquity,
        /** 支付其他与筹资活动有关的现金 */
        @JsonProperty("PAY_OTHER_FINANCE") BigDecimal payOtherFinance,
        /** 子公司减资支付给少数股东的现金 */
        @JsonProperty("SUBSIDIARY_REDUCE_CASH") BigDecimal subsidiaryReduceCash,
        /** 筹资活动现金流出其他项目 */
        @JsonProperty("FINANCE_OUTFLOW_OTHER") BigDecimal financeOutflowOther,
        /** 筹资活动现金流出平衡项目 */
        @JsonProperty("FINANCE_OUTFLOW_BALANCE") BigDecimal financeOutflowBalance,
        /** 筹资活动现金流出小计 */
        @JsonProperty("TOTAL_FINANCE_OUTFLOW") BigDecimal totalFinanceOutflow,
        /** 筹资活动产生的现金流量净额其他项目 */
        @JsonProperty("FINANCE_NETCASH_OTHER") BigDecimal financeNetcashOther,
        /** 筹资活动产生的现金流量净额平衡项目 */
        @JsonProperty("FINANCE_NETCASH_BALANCE") BigDecimal financeNetcashBalance,
        /** 筹资活动产生的现金流量净额 */
        @JsonProperty("NETCASH_FINANCE") BigDecimal netcashFinance,
        /** 汇率变动对现金及现金等价物的影响 */
        @JsonProperty("RATE_CHANGE_EFFECT") BigDecimal rateChangeEffect,
        /** 现金及现金等价物净增加额其他项目 */
        @JsonProperty("CCE_ADD_OTHER") BigDecimal cceAddOther,
        /** 现金及现金等价物净增加额平衡项目 */
        @JsonProperty("CCE_ADD_BALANCE") BigDecimal cceAddBalance,
        /** 现金及现金等价物净增加额 */
        @JsonProperty("CCE_ADD") BigDecimal cceAdd,
        /** 期初现金及现金等价物余额 */
        @JsonProperty("BEGIN_CCE") BigDecimal beginCce,
        /** 期末现金及现金等价物余额其他项目 */
        @JsonProperty("END_CCE_OTHER") BigDecimal endCceOther,
        /** 期末现金及现金等价物余额平衡项目 */
        @JsonProperty("END_CCE_BALANCE") BigDecimal endCceBalance,
        /** 期末现金及现金等价物余额 */
        @JsonProperty("END_CCE") BigDecimal endCce,
        /** 净利润（间接法补充资料） */
        @JsonProperty("NETPROFIT") BigDecimal netprofit,
        /** 资产减值准备 */
        @JsonProperty("ASSET_IMPAIRMENT") BigDecimal assetImpairment,
        /** 固定资产折旧、油气资产折耗、生产性生物资产折旧 */
        @JsonProperty("FA_IR_DEPR") BigDecimal faIrDepr,
        /** 油气资产折耗、生产性生物资产折旧 */
        @JsonProperty("OILGAS_BIOLOGY_DEPR") BigDecimal oilgasBiologyDepr,
        /** 投资性房地产折旧 */
        @JsonProperty("IR_DEPR") BigDecimal irDepr,
        /** 无形资产摊销 */
        @JsonProperty("IA_AMORTIZE") BigDecimal iaAmortize,
        /** 长期待摊费用摊销 */
        @JsonProperty("LPE_AMORTIZE") BigDecimal lpeAmortize,
        /** 递延收益摊销 */
        @JsonProperty("DEFER_INCOME_AMORTIZE") BigDecimal deferIncomeAmortize,
        /** 待摊费用减少 */
        @JsonProperty("PREPAID_EXPENSE_REDUCE") BigDecimal prepaidExpenseReduce,
        /** 预提费用增加 */
        @JsonProperty("ACCRUED_EXPENSE_ADD") BigDecimal accruedExpenseAdd,
        /** 处置固定资产、无形资产和其他长期资产的损失 */
        @JsonProperty("DISPOSAL_LONGASSET_LOSS") BigDecimal disposalLongassetLoss,
        /** 固定资产报废损失 */
        @JsonProperty("FA_SCRAP_LOSS") BigDecimal faScrapLoss,
        /** 公允价值变动损失 */
        @JsonProperty("FAIRVALUE_CHANGE_LOSS") BigDecimal fairvalueChangeLoss,
        /** 财务费用 */
        @JsonProperty("FINANCE_EXPENSE") BigDecimal financeExpense,
        /** 投资损失 */
        @JsonProperty("INVEST_LOSS") BigDecimal investLoss,
        /** 递延所得税 */
        @JsonProperty("DEFER_TAX") BigDecimal deferTax,
        /** 递延所得税资产减少 */
        @JsonProperty("DT_ASSET_REDUCE") BigDecimal dtAssetReduce,
        /** 递延所得税负债增加 */
        @JsonProperty("DT_LIAB_ADD") BigDecimal dtLiabAdd,
        /** 预计负债增加 */
        @JsonProperty("PREDICT_LIAB_ADD") BigDecimal predictLiabAdd,
        /** 存货的减少 */
        @JsonProperty("INVENTORY_REDUCE") BigDecimal inventoryReduce,
        /** 经营性应收项目的减少 */
        @JsonProperty("OPERATE_RECE_REDUCE") BigDecimal operateReceReduce,
        /** 经营性应付项目的增加 */
        @JsonProperty("OPERATE_PAYABLE_ADD") BigDecimal operatePayableAdd,
        /** 其他（间接法调节项） */
        @JsonProperty("OTHER") BigDecimal other,
        /** 经营活动现金流量净额其他（附注） */
        @JsonProperty("OPERATE_NETCASH_OTHERNOTE") BigDecimal operateNetcashOthernote,
        /** 经营活动现金流量净额平衡（附注） */
        @JsonProperty("OPERATE_NETCASH_BALANCENOTE") BigDecimal operateNetcashBalancenote,
        /** 经营活动产生的现金流量净额（附注） */
        @JsonProperty("NETCASH_OPERATENOTE") BigDecimal netcashOperatenote,
        /** 债务转为资本 */
        @JsonProperty("DEBT_TRANSFER_CAPITAL") BigDecimal debtTransferCapital,
        /** 一年内到期的可转换公司债券 */
        @JsonProperty("CONVERT_BOND_1YEAR") BigDecimal convertBond1year,
        /** 融资租入固定资产 */
        @JsonProperty("FINLEASE_OBTAIN_FA") BigDecimal finleaseObtainFa,
        /** 不涉及现金收支的投资和筹资活动其他 */
        @JsonProperty("UNINVOLVE_INVESTFIN_OTHER") BigDecimal uninvolveInvestfinOther,
        /** 现金的期末余额 */
        @JsonProperty("END_CASH") BigDecimal endCash,
        /** 现金的期初余额 */
        @JsonProperty("BEGIN_CASH") BigDecimal beginCash,
        /** 现金等价物的期末余额 */
        @JsonProperty("END_CASH_EQUIVALENTS") BigDecimal endCashEquivalents,
        /** 现金等价物的期初余额 */
        @JsonProperty("BEGIN_CASH_EQUIVALENTS") BigDecimal beginCashEquivalents,
        /** 现金及现金等价物净增加额其他（附注） */
        @JsonProperty("CCE_ADD_OTHERNOTE") BigDecimal cceAddOthernote,
        /** 现金及现金等价物净增加额平衡（附注） */
        @JsonProperty("CCE_ADD_BALANCENOTE") BigDecimal cceAddBalancenote,
        /** 现金及现金等价物净增加额（附注） */
        @JsonProperty("CCE_ADDNOTE") BigDecimal cceAddnote,
        /** 销售商品、提供劳务收到的现金，同比（%） */
        @JsonProperty("SALES_SERVICES_YOY") BigDecimal salesServicesYoy,
        /** 客户存款和同业存放款项净增加额，同比（%） */
        @JsonProperty("DEPOSIT_INTERBANK_ADD_YOY") BigDecimal depositInterbankAddYoy,
        /** 向中央银行借款净增加额，同比（%） */
        @JsonProperty("LOAN_PBC_ADD_YOY") BigDecimal loanPbcAddYoy,
        /** 向其他金融机构拆入资金净增加额，同比（%） */
        @JsonProperty("OFI_BF_ADD_YOY") BigDecimal ofiBfAddYoy,
        /** 收到原保险合同保费取得的现金，同比（%） */
        @JsonProperty("RECEIVE_ORIGIC_PREMIUM_YOY") BigDecimal receiveOrigicPremiumYoy,
        /** 收到再保险业务现金净额，同比（%） */
        @JsonProperty("RECEIVE_REINSURE_NET_YOY") BigDecimal receiveReinsureNetYoy,
        /** 保户储金及投资款净增加额，同比（%） */
        @JsonProperty("INSURED_INVEST_ADD_YOY") BigDecimal insuredInvestAddYoy,
        /** 处置交易性金融资产净增加额，同比（%） */
        @JsonProperty("DISPOSAL_TFA_ADD_YOY") BigDecimal disposalTfaAddYoy,
        /** 收取利息、手续费及佣金的现金，同比（%） */
        @JsonProperty("RECEIVE_INTEREST_COMMISSION_YOY") BigDecimal receiveInterestCommissionYoy,
        /** 拆入资金净增加额，同比（%） */
        @JsonProperty("BORROW_FUND_ADD_YOY") BigDecimal borrowFundAddYoy,
        /** 发放贷款及垫款净减少额，同比（%） */
        @JsonProperty("LOAN_ADVANCE_REDUCE_YOY") BigDecimal loanAdvanceReduceYoy,
        /** 回购业务资金净增加额，同比（%） */
        @JsonProperty("REPO_BUSINESS_ADD_YOY") BigDecimal repoBusinessAddYoy,
        /** 收到的税费返还，同比（%） */
        @JsonProperty("RECEIVE_TAX_REFUND_YOY") BigDecimal receiveTaxRefundYoy,
        /** 收到其他与经营活动有关的现金，同比（%） */
        @JsonProperty("RECEIVE_OTHER_OPERATE_YOY") BigDecimal receiveOtherOperateYoy,
        /** 经营活动现金流入其他项目，同比（%） */
        @JsonProperty("OPERATE_INFLOW_OTHER_YOY") BigDecimal operateInflowOtherYoy,
        /** 经营活动现金流入平衡项目，同比（%） */
        @JsonProperty("OPERATE_INFLOW_BALANCE_YOY") BigDecimal operateInflowBalanceYoy,
        /** 经营活动现金流入小计，同比（%） */
        @JsonProperty("TOTAL_OPERATE_INFLOW_YOY") BigDecimal totalOperateInflowYoy,
        /** 购买商品、接受劳务支付的现金，同比（%） */
        @JsonProperty("BUY_SERVICES_YOY") BigDecimal buyServicesYoy,
        /** 客户贷款及垫款净增加额，同比（%） */
        @JsonProperty("LOAN_ADVANCE_ADD_YOY") BigDecimal loanAdvanceAddYoy,
        /** 存放中央银行和同业款项净增加额，同比（%） */
        @JsonProperty("PBC_INTERBANK_ADD_YOY") BigDecimal pbcInterbankAddYoy,
        /** 支付原保险合同赔付款项的现金，同比（%） */
        @JsonProperty("PAY_ORIGIC_COMPENSATE_YOY") BigDecimal payOrigicCompensateYoy,
        /** 支付利息、手续费及佣金的现金，同比（%） */
        @JsonProperty("PAY_INTEREST_COMMISSION_YOY") BigDecimal payInterestCommissionYoy,
        /** 支付保单红利的现金，同比（%） */
        @JsonProperty("PAY_POLICY_BONUS_YOY") BigDecimal payPolicyBonusYoy,
        /** 支付给职工以及为职工支付的现金，同比（%） */
        @JsonProperty("PAY_STAFF_CASH_YOY") BigDecimal payStaffCashYoy,
        /** 支付的各项税费，同比（%） */
        @JsonProperty("PAY_ALL_TAX_YOY") BigDecimal payAllTaxYoy,
        /** 支付其他与经营活动有关的现金，同比（%） */
        @JsonProperty("PAY_OTHER_OPERATE_YOY") BigDecimal payOtherOperateYoy,
        /** 经营活动现金流出其他项目，同比（%） */
        @JsonProperty("OPERATE_OUTFLOW_OTHER_YOY") BigDecimal operateOutflowOtherYoy,
        /** 经营活动现金流出平衡项目，同比（%） */
        @JsonProperty("OPERATE_OUTFLOW_BALANCE_YOY") BigDecimal operateOutflowBalanceYoy,
        /** 经营活动现金流出小计，同比（%） */
        @JsonProperty("TOTAL_OPERATE_OUTFLOW_YOY") BigDecimal totalOperateOutflowYoy,
        /** 经营活动产生的现金流量净额其他项目，同比（%） */
        @JsonProperty("OPERATE_NETCASH_OTHER_YOY") BigDecimal operateNetcashOtherYoy,
        /** 经营活动产生的现金流量净额平衡项目，同比（%） */
        @JsonProperty("OPERATE_NETCASH_BALANCE_YOY") BigDecimal operateNetcashBalanceYoy,
        /** 经营活动产生的现金流量净额，同比（%） */
        @JsonProperty("NETCASH_OPERATE_YOY") BigDecimal netcashOperateYoy,
        /** 收回投资收到的现金，同比（%） */
        @JsonProperty("WITHDRAW_INVEST_YOY") BigDecimal withdrawInvestYoy,
        /** 取得投资收益收到的现金，同比（%） */
        @JsonProperty("RECEIVE_INVEST_INCOME_YOY") BigDecimal receiveInvestIncomeYoy,
        /** 处置固定资产、无形资产和其他长期资产收回的现金净额，同比（%） */
        @JsonProperty("DISPOSAL_LONG_ASSET_YOY") BigDecimal disposalLongAssetYoy,
        /** 处置子公司及其他营业单位收到的现金净额，同比（%） */
        @JsonProperty("DISPOSAL_SUBSIDIARY_OTHER_YOY") BigDecimal disposalSubsidiaryOtherYoy,
        /** 减少质押和定期存款所收到的现金，同比（%） */
        @JsonProperty("REDUCE_PLEDGE_TIMEDEPOSITS_YOY") BigDecimal reducePledgeTimedepositsYoy,
        /** 收到其他与投资活动有关的现金，同比（%） */
        @JsonProperty("RECEIVE_OTHER_INVEST_YOY") BigDecimal receiveOtherInvestYoy,
        /** 投资活动现金流入其他项目，同比（%） */
        @JsonProperty("INVEST_INFLOW_OTHER_YOY") BigDecimal investInflowOtherYoy,
        /** 投资活动现金流入平衡项目，同比（%） */
        @JsonProperty("INVEST_INFLOW_BALANCE_YOY") BigDecimal investInflowBalanceYoy,
        /** 投资活动现金流入小计，同比（%） */
        @JsonProperty("TOTAL_INVEST_INFLOW_YOY") BigDecimal totalInvestInflowYoy,
        /** 购建固定资产、无形资产和其他长期资产支付的现金，同比（%） */
        @JsonProperty("CONSTRUCT_LONG_ASSET_YOY") BigDecimal constructLongAssetYoy,
        /** 投资支付的现金，同比（%） */
        @JsonProperty("INVEST_PAY_CASH_YOY") BigDecimal investPayCashYoy,
        /** 质押贷款净增加额，同比（%） */
        @JsonProperty("PLEDGE_LOAN_ADD_YOY") BigDecimal pledgeLoanAddYoy,
        /** 取得子公司及其他营业单位支付的现金净额，同比（%） */
        @JsonProperty("OBTAIN_SUBSIDIARY_OTHER_YOY") BigDecimal obtainSubsidiaryOtherYoy,
        /** 增加质押和定期存款所支付的现金，同比（%） */
        @JsonProperty("ADD_PLEDGE_TIMEDEPOSITS_YOY") BigDecimal addPledgeTimedepositsYoy,
        /** 支付其他与投资活动有关的现金，同比（%） */
        @JsonProperty("PAY_OTHER_INVEST_YOY") BigDecimal payOtherInvestYoy,
        /** 投资活动现金流出其他项目，同比（%） */
        @JsonProperty("INVEST_OUTFLOW_OTHER_YOY") BigDecimal investOutflowOtherYoy,
        /** 投资活动现金流出平衡项目，同比（%） */
        @JsonProperty("INVEST_OUTFLOW_BALANCE_YOY") BigDecimal investOutflowBalanceYoy,
        /** 投资活动现金流出小计，同比（%） */
        @JsonProperty("TOTAL_INVEST_OUTFLOW_YOY") BigDecimal totalInvestOutflowYoy,
        /** 投资活动产生的现金流量净额其他项目，同比（%） */
        @JsonProperty("INVEST_NETCASH_OTHER_YOY") BigDecimal investNetcashOtherYoy,
        /** 投资活动产生的现金流量净额平衡项目，同比（%） */
        @JsonProperty("INVEST_NETCASH_BALANCE_YOY") BigDecimal investNetcashBalanceYoy,
        /** 投资活动产生的现金流量净额，同比（%） */
        @JsonProperty("NETCASH_INVEST_YOY") BigDecimal netcashInvestYoy,
        /** 吸收投资收到的现金，同比（%） */
        @JsonProperty("ACCEPT_INVEST_CASH_YOY") BigDecimal acceptInvestCashYoy,
        /** 其中：子公司吸收少数股东投资收到的现金，同比（%） */
        @JsonProperty("SUBSIDIARY_ACCEPT_INVEST_YOY") BigDecimal subsidiaryAcceptInvestYoy,
        /** 取得借款收到的现金，同比（%） */
        @JsonProperty("RECEIVE_LOAN_CASH_YOY") BigDecimal receiveLoanCashYoy,
        /** 发行债券收到的现金，同比（%） */
        @JsonProperty("ISSUE_BOND_YOY") BigDecimal issueBondYoy,
        /** 收到其他与筹资活动有关的现金，同比（%） */
        @JsonProperty("RECEIVE_OTHER_FINANCE_YOY") BigDecimal receiveOtherFinanceYoy,
        /** 筹资活动现金流入其他项目，同比（%） */
        @JsonProperty("FINANCE_INFLOW_OTHER_YOY") BigDecimal financeInflowOtherYoy,
        /** 筹资活动现金流入平衡项目，同比（%） */
        @JsonProperty("FINANCE_INFLOW_BALANCE_YOY") BigDecimal financeInflowBalanceYoy,
        /** 筹资活动现金流入小计，同比（%） */
        @JsonProperty("TOTAL_FINANCE_INFLOW_YOY") BigDecimal totalFinanceInflowYoy,
        /** 偿还债务支付的现金，同比（%） */
        @JsonProperty("PAY_DEBT_CASH_YOY") BigDecimal payDebtCashYoy,
        /** 分配股利、利润或偿付利息支付的现金，同比（%） */
        @JsonProperty("ASSIGN_DIVIDEND_PORFIT_YOY") BigDecimal assignDividendPorfitYoy,
        /** 其中：子公司支付给少数股东的股利、利润，同比（%） */
        @JsonProperty("SUBSIDIARY_PAY_DIVIDEND_YOY") BigDecimal subsidiaryPayDividendYoy,
        /** 购买子公司少数股权支付的现金，同比（%） */
        @JsonProperty("BUY_SUBSIDIARY_EQUITY_YOY") BigDecimal buySubsidiaryEquityYoy,
        /** 支付其他与筹资活动有关的现金，同比（%） */
        @JsonProperty("PAY_OTHER_FINANCE_YOY") BigDecimal payOtherFinanceYoy,
        /** 子公司减资支付给少数股东的现金，同比（%） */
        @JsonProperty("SUBSIDIARY_REDUCE_CASH_YOY") BigDecimal subsidiaryReduceCashYoy,
        /** 筹资活动现金流出其他项目，同比（%） */
        @JsonProperty("FINANCE_OUTFLOW_OTHER_YOY") BigDecimal financeOutflowOtherYoy,
        /** 筹资活动现金流出平衡项目，同比（%） */
        @JsonProperty("FINANCE_OUTFLOW_BALANCE_YOY") BigDecimal financeOutflowBalanceYoy,
        /** 筹资活动现金流出小计，同比（%） */
        @JsonProperty("TOTAL_FINANCE_OUTFLOW_YOY") BigDecimal totalFinanceOutflowYoy,
        /** 筹资活动产生的现金流量净额其他项目，同比（%） */
        @JsonProperty("FINANCE_NETCASH_OTHER_YOY") BigDecimal financeNetcashOtherYoy,
        /** 筹资活动产生的现金流量净额平衡项目，同比（%） */
        @JsonProperty("FINANCE_NETCASH_BALANCE_YOY") BigDecimal financeNetcashBalanceYoy,
        /** 筹资活动产生的现金流量净额，同比（%） */
        @JsonProperty("NETCASH_FINANCE_YOY") BigDecimal netcashFinanceYoy,
        /** 汇率变动对现金及现金等价物的影响，同比（%） */
        @JsonProperty("RATE_CHANGE_EFFECT_YOY") BigDecimal rateChangeEffectYoy,
        /** 现金及现金等价物净增加额其他项目，同比（%） */
        @JsonProperty("CCE_ADD_OTHER_YOY") BigDecimal cceAddOtherYoy,
        /** 现金及现金等价物净增加额平衡项目，同比（%） */
        @JsonProperty("CCE_ADD_BALANCE_YOY") BigDecimal cceAddBalanceYoy,
        /** 现金及现金等价物净增加额，同比（%） */
        @JsonProperty("CCE_ADD_YOY") BigDecimal cceAddYoy,
        /** 期初现金及现金等价物余额，同比（%） */
        @JsonProperty("BEGIN_CCE_YOY") BigDecimal beginCceYoy,
        /** 期末现金及现金等价物余额其他项目，同比（%） */
        @JsonProperty("END_CCE_OTHER_YOY") BigDecimal endCceOtherYoy,
        /** 期末现金及现金等价物余额平衡项目，同比（%） */
        @JsonProperty("END_CCE_BALANCE_YOY") BigDecimal endCceBalanceYoy,
        /** 期末现金及现金等价物余额，同比（%） */
        @JsonProperty("END_CCE_YOY") BigDecimal endCceYoy,
        /** 净利润（间接法补充资料），同比（%） */
        @JsonProperty("NETPROFIT_YOY") BigDecimal netprofitYoy,
        /** 资产减值准备，同比（%） */
        @JsonProperty("ASSET_IMPAIRMENT_YOY") BigDecimal assetImpairmentYoy,
        /** 固定资产折旧、油气资产折耗、生产性生物资产折旧，同比（%） */
        @JsonProperty("FA_IR_DEPR_YOY") BigDecimal faIrDeprYoy,
        /** 油气资产折耗、生产性生物资产折旧，同比（%） */
        @JsonProperty("OILGAS_BIOLOGY_DEPR_YOY") BigDecimal oilgasBiologyDeprYoy,
        /** 投资性房地产折旧，同比（%） */
        @JsonProperty("IR_DEPR_YOY") BigDecimal irDeprYoy,
        /** 无形资产摊销，同比（%） */
        @JsonProperty("IA_AMORTIZE_YOY") BigDecimal iaAmortizeYoy,
        /** 长期待摊费用摊销，同比（%） */
        @JsonProperty("LPE_AMORTIZE_YOY") BigDecimal lpeAmortizeYoy,
        /** 递延收益摊销，同比（%） */
        @JsonProperty("DEFER_INCOME_AMORTIZE_YOY") BigDecimal deferIncomeAmortizeYoy,
        /** 待摊费用减少，同比（%） */
        @JsonProperty("PREPAID_EXPENSE_REDUCE_YOY") BigDecimal prepaidExpenseReduceYoy,
        /** 预提费用增加，同比（%） */
        @JsonProperty("ACCRUED_EXPENSE_ADD_YOY") BigDecimal accruedExpenseAddYoy,
        /** 处置固定资产、无形资产和其他长期资产的损失，同比（%） */
        @JsonProperty("DISPOSAL_LONGASSET_LOSS_YOY") BigDecimal disposalLongassetLossYoy,
        /** 固定资产报废损失，同比（%） */
        @JsonProperty("FA_SCRAP_LOSS_YOY") BigDecimal faScrapLossYoy,
        /** 公允价值变动损失，同比（%） */
        @JsonProperty("FAIRVALUE_CHANGE_LOSS_YOY") BigDecimal fairvalueChangeLossYoy,
        /** 财务费用，同比（%） */
        @JsonProperty("FINANCE_EXPENSE_YOY") BigDecimal financeExpenseYoy,
        /** 投资损失，同比（%） */
        @JsonProperty("INVEST_LOSS_YOY") BigDecimal investLossYoy,
        /** 递延所得税，同比（%） */
        @JsonProperty("DEFER_TAX_YOY") BigDecimal deferTaxYoy,
        /** 递延所得税资产减少，同比（%） */
        @JsonProperty("DT_ASSET_REDUCE_YOY") BigDecimal dtAssetReduceYoy,
        /** 递延所得税负债增加，同比（%） */
        @JsonProperty("DT_LIAB_ADD_YOY") BigDecimal dtLiabAddYoy,
        /** 预计负债增加，同比（%） */
        @JsonProperty("PREDICT_LIAB_ADD_YOY") BigDecimal predictLiabAddYoy,
        /** 存货的减少，同比（%） */
        @JsonProperty("INVENTORY_REDUCE_YOY") BigDecimal inventoryReduceYoy,
        /** 经营性应收项目的减少，同比（%） */
        @JsonProperty("OPERATE_RECE_REDUCE_YOY") BigDecimal operateReceReduceYoy,
        /** 经营性应付项目的增加，同比（%） */
        @JsonProperty("OPERATE_PAYABLE_ADD_YOY") BigDecimal operatePayableAddYoy,
        /** 其他（间接法调节项），同比（%） */
        @JsonProperty("OTHER_YOY") BigDecimal otherYoy,
        /** 经营活动现金流量净额其他（附注），同比（%） */
        @JsonProperty("OPERATE_NETCASH_OTHERNOTE_YOY") BigDecimal operateNetcashOthernoteYoy,
        /** 经营活动现金流量净额平衡（附注），同比（%） */
        @JsonProperty("OPERATE_NETCASH_BALANCENOTE_YOY") BigDecimal operateNetcashBalancenoteYoy,
        /** 经营活动产生的现金流量净额（附注），同比（%） */
        @JsonProperty("NETCASH_OPERATENOTE_YOY") BigDecimal netcashOperatenoteYoy,
        /** 债务转为资本，同比（%） */
        @JsonProperty("DEBT_TRANSFER_CAPITAL_YOY") BigDecimal debtTransferCapitalYoy,
        /** 一年内到期的可转换公司债券，同比（%） */
        @JsonProperty("CONVERT_BOND_1YEAR_YOY") BigDecimal convertBond1yearYoy,
        /** 融资租入固定资产，同比（%） */
        @JsonProperty("FINLEASE_OBTAIN_FA_YOY") BigDecimal finleaseObtainFaYoy,
        /** 不涉及现金收支的投资和筹资活动其他，同比（%） */
        @JsonProperty("UNINVOLVE_INVESTFIN_OTHER_YOY") BigDecimal uninvolveInvestfinOtherYoy,
        /** 现金的期末余额，同比（%） */
        @JsonProperty("END_CASH_YOY") BigDecimal endCashYoy,
        /** 现金的期初余额，同比（%） */
        @JsonProperty("BEGIN_CASH_YOY") BigDecimal beginCashYoy,
        /** 现金等价物的期末余额，同比（%） */
        @JsonProperty("END_CASH_EQUIVALENTS_YOY") BigDecimal endCashEquivalentsYoy,
        /** 现金等价物的期初余额，同比（%） */
        @JsonProperty("BEGIN_CASH_EQUIVALENTS_YOY") BigDecimal beginCashEquivalentsYoy,
        /** 现金及现金等价物净增加额其他（附注），同比（%） */
        @JsonProperty("CCE_ADD_OTHERNOTE_YOY") BigDecimal cceAddOthernoteYoy,
        /** 现金及现金等价物净增加额平衡（附注），同比（%） */
        @JsonProperty("CCE_ADD_BALANCENOTE_YOY") BigDecimal cceAddBalancenoteYoy,
        /** 现金及现金等价物净增加额（附注），同比（%） */
        @JsonProperty("CCE_ADDNOTE_YOY") BigDecimal cceAddnoteYoy,
        /** 审计意见类型 */
        @JsonProperty("OPINION_TYPE") String opinionType,
        /** 其他审计意见类型 */
        @JsonProperty("OSOPINION_TYPE") String osopinionType,
        /** 少数股东权益（间接法调节项） */
        @JsonProperty("MINORITY_INTEREST") BigDecimal minorityInterest,
        /** 少数股东权益（间接法调节项），同比（%） */
        @JsonProperty("MINORITY_INTEREST_YOY") BigDecimal minorityInterestYoy,
        /** 使用权资产摊销 */
        @JsonProperty("USERIGHT_ASSET_AMORTIZE") BigDecimal userightAssetAmortize,
        /** 使用权资产摊销，同比（%） */
        @JsonProperty("USERIGHT_ASSET_AMORTIZE_YOY") BigDecimal userightAssetAmortizeYoy
) {
}
